---
title: "16 Existing project, GitHub first"
author: "Boukara Ahmed El-Hachemi"
date: "03/07/2020"
output:
  github_document: default
---

A novice-friendly workflow for bringing an existing R project into the RStudio and Git/GitHub universe.   

We do this in a slightly awkward way, in order to avoid using Git at the command line. You won’t want to work this way forever, but it’s perfectly fine as you’re getting started!   

We assume you’ve got your existing R project isolated in a directory on your computer. If that’s not already true, make it so.   

## 1 Make a repo on GitHub   

## 2 New RStudio Project via git clone  

## 3 Bring your existing project over  

Using your favorite method of moving or copying files, copy the files that constitute your existing project into the directory for this new project.   

In RStudio, consult the Git pane and the file browser.   

* Are you seeing all the files? They should be here if your move/copy was successful.  
* Are they showing up in the Git pane with questions marks? They should be appearing as new untracked files.    

## 4 Stage and commit

Commit your files to this repo. How?   

* Click the “Git” tab in upper right pane  
* Check “Staged” box for all files you want to commit.  
  * Default: stage it.  
  * When to reconsider: this will all go to GitHub. So do consider if that is appropriate for each file. **You can absolutely keep a file locally, without committing it to the Git repo and sending to GitHub**. Just let it sit there in your Git pane, without being staged. No harm will be done. If this is a long-term situation, list the file in `.gitignore`.   
* If you’re not already in the Git pop-up, click “Commit”   
* Type a message in “Commit message”, such as “init”.  
* Click “Commit”   

## 5 Push your local changes to GitHub

Click the green “Push” button to send your local changes to GitHub.  

## 6 Confirm the local change propagated to the GitHub remote

## 7 The end

